apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    app: gop-fileserver
spec:
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
  containers:
  - name: jekyll
    image: kodekloud/fileserver
    volumeMounts:
    - name: data-store
      mountPath: /web

---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    app: gop-fileserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31200
